name: eco-tech-h2gam
channels:
  - conda-forge
  - defaults
dependencies:
  - conda=4.10.3
  - python=3.8
  - pip
  # Add other dependencies from your requirements.txt file
  - pip:
    - -r requirements.txt
    - cdsapi
    - regionmask
    - cartopy

